markbeep/AudioBookRequest

app/internal/prowlarr/prowlarr.py

Closes #10 
Fixes trailing slashes in prowlarr base urls

Remove trailing slash prowlarr base url problem

---

README.md
app/internal/book_search.py
app/routers/search.py
templates/search.html

Adds audible link to seach results

---

app/internal/models.py
app/routers/wishlist.py
app/util/auth.py
templates/wishlist_page/wishlist.html

add title attribute to show who requested a book

---

app/internal/models.py
app/internal/prowlarr/prowlarr.py
templates/wishlist_page/sources.html

make infourl optional and add logging

---

app/internal/auth/authentication.py
app/main.py
app/routers/auth.py
app/routers/settings.py
app/util/toast.py
pyproject.toml
templates/base.html
templates/login.html
templates/manual.html
templates/settings_page/account.html
templates/settings_page/download.html
templates/settings_page/prowlarr.html
templates/settings_page/security.html
templates/settings_page/users.html

standardize raising errors and having them show up as toasts

---

app/internal/auth/oidc_config.py
app/routers/settings.py

make end_session_endpoint optional

---

.github/workflows/build.yaml
Dockerfile
app/internal/auth/oidc_config.py
app/internal/env_settings.py
app/routers/settings.py
docker-compose.yml
templates/settings_page/base.html

add version to settings pages

---

README.md
app/internal/env_settings.py
app/internal/models.py
app/internal/notifications.py
app/internal/prowlarr/prowlarr.py
app/main.py

add logging and correctly join urls for prowlarr

---

app/internal/auth/oidc_config.py
app/routers/auth.py
app/routers/settings.py
templates/settings_page/security.html

add options for using https on redirect url and adding logout url

---

app/routers/auth.py

add random string to state

---

app/internal/book_search.py
app/routers/search.py

add audimeta metadata server (and adds brazilian region)

---

app/internal/indexers/abstract.py
app/internal/indexers/indexer_util.py
app/internal/indexers/mam.py
app/routers/settings.py

Indexers couldn't be disabled before. This fixes that and also prevents the logs from being filled with message about inactive indexers.

fix not being able to disable indexers

---

.github/workflows/nix-build.yaml
Dockerfile
app/main.py
app/routers/root.py
app/util/fetch_js.py
flake.nix
pyproject.toml
static/.gitignore
templates/base.html
templates/scripts/alpinejs.html
templates/settings_page/download.html
uv.lock

load js dependencies into docker image

---

app/main.py
app/routers/root.py
app/routers/settings.py
app/util/fetch_js.py
app/util/templates.py
flake.nix
static/.gitignore
templates/base.html
templates/scripts/alpinejs.html
templates/scripts/toast.html
templates/settings_page/download.html
templates/settings_page/users.html
templates/wishlist_page/sources.html
templates/wishlist_page/wishlist.html

Fixes wrong handling of special characters in names and other parameters

---

app/internal/notifications.py
app/routers/root.py
app/routers/settings.py
app/util/templates.py
templates/icons/pencil.html
templates/settings_page/notifications.html

allow editing notifications

---

.env.local
README.md
app/internal/env_settings.py
app/main.py
app/routers/auth.py
app/routers/root.py
app/routers/wishlist.py
app/util/redirect.py
app/util/templates.py
templates/base.html
templates/init.html
templates/invalid_oidc.html
templates/login.html
templates/manual.html
templates/scripts/alpinejs.html
templates/scripts/toast.html
templates/search.html
templates/settings_page/account.html
templates/settings_page/base.html
templates/settings_page/download.html
templates/settings_page/indexers.html
templates/settings_page/notifications.html
templates/settings_page/prowlarr.html
templates/settings_page/security.html
templates/settings_page/users.html
templates/wishlist_page/base_wishlist.html
templates/wishlist_page/manual.html
templates/wishlist_page/sources.html
templates/wishlist_page/wishlist.html

add option to configure base url

---

app/internal/notifications.py
app/routers/search.py
app/routers/settings.py
app/routers/wishlist.py

send notifications when manually setting request as "downloaded"

---

app/internal/prowlarr/prowlarr.py
app/routers/settings.py
templates/settings_page/prowlarr.html

Closes #93 
Closes #43 (testing the indexers endpoint automatically serves as a way to test the prowlarr settings)

correctly handle missing/incorrect prowlarr settings

---

templates/search.html

fix overlapping border

---

.env.local
README.md
app/internal/book_search.py
app/internal/env_settings.py
app/routers/search.py
docs/content/docs/concepts/environment-variables.md

add default region env variable
